version: 2

models:
  - name: link_sf_subscription__brand
    description: "Table de liaison entre les abonnements Salesforce et les marques"
    columns:
      - name: sf_subscription__brand_hk
        description: "Clé de hachage unique pour la liaison abonnement-marque"
        tests:
          - not_null
          - unique
      - name: load_dts
        description: "Date de chargement"
        tests:
          - not_null
      - name: record_src
        description: "Source des données"
        tests:
          - not_null
      - name: dv_runid
        description: "Identifiant d'exécution Data Vault"
        tests:
          - not_null
      - name: sf_subscription_hk
        description: "Clé de hachage de l'abonnement Salesforce"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_sf_subscription')
              field: sf_subscription_hk
      - name: brand_hk
        description: "Clé de hachage de la marque"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_brand')
              field: brand_hk

sources:
  - name: dv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: link_sf_subscription__brand
        description: "Table de liaison entre les abonnements Salesforce et les marques"
        columns:
          - name: sf_subscription__brand_hk
            description: "Clé de hachage unique pour la liaison abonnement-marque"
          - name: load_dts
            description: "Date de chargement"
          - name: record_src
            description: "Source des données"
          - name: dv_runid
            description: "Identifiant d'exécution Data Vault"
          - name: sf_subscription_hk
            description: "Clé de hachage de l'abonnement Salesforce"
          - name: brand_hk
            description: "Clé de hachage de la marque"

  - name: link_booking__item__cruise__vessel__cabin
    description: "Table de liaison entre les réservations, les éléments, les croisières, les navires et les cabines"
    columns:
      - name: booking__item__cruise__vessel__cabin_hk
        description: "Clé de hachage unique de la liaison"
        tests:
          - not_null
          - unique
      - name: load_dts
        description: "Date de chargement"
        tests:
          - not_null
      - name: record_src
        description: "Source des données"
        tests:
          - not_null
      - name: dv_runid
        description: "Identifiant d'exécution Data Vault"
        tests:
          - not_null
      - name: booking_hk
        description: "Clé de hachage de la réservation"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_booking')
              field: booking_hk
      - name: item_hk
        description: "Clé de hachage de l'élément"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_item')
              field: item_hk
      - name: cruise_hk
        description: "Clé de hachage de la croisière"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_cruise')
              field: cruise_hk
      - name: vessel_hk
        description: "Clé de hachage du navire"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_vessel')
              field: vessel_hk
      - name: cabin_hk
        description: "Clé de hachage de la cabine"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_cabin')
              field: cabin_hk

sources:
  - name: dv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: link_booking__item__cruise__vessel__cabin
        description: "Table de liaison entre les réservations, les éléments, les croisières, les navires et les cabines"
        columns:
          - name: booking__item__cruise__vessel__cabin_hk
            description: "Clé de hachage unique de la liaison"
          - name: load_dts
            description: "Date de chargement"
          - name: record_src
            description: "Source des données"
          - name: dv_runid
            description: "Identifiant d'exécution Data Vault"
          - name: booking_hk
            description: "Clé de hachage de la réservation"
          - name: item_hk
            description: "Clé de hachage de l'élément"
          - name: cruise_hk
            description: "Clé de hachage de la croisière"
          - name: vessel_hk
            description: "Clé de hachage du navire"
          - name: cabin_hk
            description: "Clé de hachage de la cabine"

  - name: link_cabincat__mr_cabin_number__mr_vesconfig
    description: "Table de liaison entre les catégories de cabines, les numéros de cabines et les configurations des navires"
    columns:
      - name: cabincat__mr_cabin_number__mr_vessel_configuration_hk
        description: "Clé de hachage de la liaison"
        tests:
          - not_null
          - unique
      - name: load_dts
        description: "Date de chargement"
        tests:
          - not_null
      - name: record_src
        description: "Source des données"
        tests:
          - not_null
      - name: dv_runid
        description: "Identifiant d'exécution"
        tests:
          - not_null
      - name: mr_cabin_number_hk
        description: "Clé de hachage du numéro de cabine"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_mr_cabin_number')
              field: mr_cabin_number_hk
      - name: mr_vessel_configuration_hk
        description: "Clé de hachage de la configuration du navire"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_mr_vessel_configuration')
              field: mr_vessel_configuration_hk
      - name: cabin_category_hk
        description: "Clé de hachage de la catégorie de cabine"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_cabin_category')
              field: cabin_category_hk

sources:
  - name: dv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: hub_mr_cabin_number
        description: "Table hub des numéros de cabine"
      - name: hub_mr_vessel_configuration
        description: "Table hub des configurations des navires"
      - name: hub_cabin_category
        description: "Table hub des catégories de cabine"

  - name: link_configuration__mr_vessel__mr_vessel_configuration
    description: "Table de liaison entre les configurations, les navires et leurs configurations"
    columns:
      - name: configuration__mr_vessel__mr_vessel_configuration_hk
        description: "Clé de hachage de la liaison"
        tests:
          - not_null
          - unique
      - name: load_dts
        description: "Date de chargement"
        tests:
          - not_null
      - name: record_src
        description: "Source des données"
        tests:
          - not_null
      - name: dv_runid
        description: "Identifiant d'exécution"
        tests:
          - not_null
      - name: configuration_hk
        description: "Clé de hachage de la configuration"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_configuration')
              field: configuration_hk
      - name: mr_vessel_configuration_hk
        description: "Clé de hachage de la configuration du navire"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_mr_vessel_configuration')
              field: mr_vessel_configuration_hk
      - name: mr_vessel_hk
        description: "Clé de hachage du navire"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_mr_vessel')
              field: mr_vessel_hk

sources:
  - name: dv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: hub_configuration
        description: "Table hub des configurations"
      - name: hub_mr_vessel_configuration
        description: "Table hub des configurations des navires"
      - name: hub_mr_vessel
        description: "Table hub des navires"

  - name: link_vessel__mr_vessel__mr_vessel_type
    description: "Table de liaison entre les navires, les navires MR et leurs types"
    columns:
      - name: vessel__mr_vessel__mr_vessel_type_hk
        description: "Clé de hachage de la liaison"
        tests:
          - not_null
          - unique
      - name: load_dts
        description: "Date de chargement"
        tests:
          - not_null
      - name: record_src
        description: "Source des données"
        tests:
          - not_null
      - name: dv_runid
        description: "Identifiant d'exécution"
        tests:
          - not_null
      - name: vessel_hk
        description: "Clé de hachage du navire"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_vessel')
              field: vessel_hk
      - name: mr_vessel_hk
        description: "Clé de hachage du navire MR"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_mr_vessel')
              field: mr_vessel_hk
      - name: mr_vessel_type_hk
        description: "Clé de hachage du type de navire"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_mr_vessel_type')
              field: mr_vessel_type_hk

sources:
  - name: dv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: hub_vessel
        description: "Table hub des navires"
      - name: hub_mr_vessel
        description: "Table hub des navires MR"
      - name: hub_mr_vessel_type
        description: "Table hub des types de navires" 