version: 2

models:
  - name: cp_xml_validity
    description: "Table de gestion de la validité temporelle des fichiers XML de réservation"
    columns:
      - name: booking_hk
        description: "Clé de hachage de la réservation"
        tests:
          - not_null
          - unique:
              combination_of: [booking_hk, file_name]
          - relationships:
              to: source('dv', 'hub_booking')
              field: booking_hk

      - name: file_name
        description: "Nom du fichier XML"
        tests:
          - not_null

      - name: startdate
        description: "Date de début de validité"
        tests:
          - not_null
          - dbt_utils.date_after:
              datepart: day
              field: '1900-01-01'

      - name: enddate
        description: "Date de fin de validité"
        tests:
          - not_null
          - dbt_utils.date_after:
              datepart: day
              field: '1900-01-01'
          - dbt_utils.expression_is_true:
              expression: "enddate >= startdate"

  - name: cal_booking__cruise_vw
    description: "Vue calculant les indicateurs sur les croisières d'une réservation"
    columns:
      - name: booking_hk
        description: "Clé de hachage de la réservation"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_booking')
              field: booking_hk
      - name: cruise_hk
        description: "Clé de hachage de la croisière"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'hub_cruise')
              field: cruise_hk
      - name: file_name
        description: "Nom du fichier XML source"
        tests:
          - not_null
      - name: date_departure
        description: "Date de départ de la croisière"
        tests:
          - not_null
      - name: date_arrival
        description: "Date d'arrivée de la croisière"
        tests:
          - not_null
      - name: itemstatuscode
        description: "Code de statut de l'élément"
        tests:
          - not_null
      - name: n_order_cruise
        description: "Numéro d'ordre de la croisière dans la réservation"
        tests:
          - not_null
      - name: fg_first_cruise
        description: "Indicateur de première croisière (1) ou non (0)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]
      - name: fg_last_cruise
        description: "Indicateur de dernière croisière (1) ou non (0)"
        tests:
          - not_null
          - accepted_values:
              values: [0, 1]

  - name: merged_account_and_contact
    description: "Table de gestion des fusions de comptes et de contacts Salesforce"
    columns:
      - name: ACCOUNTID_OR_CONTACTID
        description: "Identifiant du compte ou contact avant fusion"
        tests:
          - not_null
      - name: ACCOUNTID_OR_CONTACTID_POST_MERGE
        description: "Identifiant du compte ou contact après fusion"
        tests:
          - not_null
      - name: ACCOUNT_OR_CONTACT_HK
        description: "Clé de hachage du compte ou contact avant fusion"
        tests:
          - not_null
      - name: ACCOUNT_OR_CONTACT_POST_MERGE_HK
        description: "Clé de hachage du compte ou contact après fusion"
        tests:
          - not_null
      - name: TYPE_OF_OBJECT_POST_MERGE
        description: "Type d'objet après fusion (Account ou Contact)"
        tests:
          - not_null
          - accepted_values:
              values: ['Account', 'Contact']

  - name: lsat_cp_booking_cruise_vw
    description: "Vue calculant les taux de change pour les croisières"
    columns:
      - name: booking__item__cruise__vessel__cabin_hk
        description: "Clé de hachage de la liaison"
        tests:
          - not_null
          - relationships:
              to: source('dv', 'lsat_cp_booking_cruise')
              field: booking__item__cruise__vessel__cabin_hk
      - name: load_dts
        description: "Date de chargement"
        tests:
          - not_null
      - name: file_name
        description: "Nom du fichier source"
        tests:
          - not_null
      - name: opening_exchangerate_EUR
        description: "Taux de change réel vers EUR"
      - name: futur_exchangerate
        description: "Taux de change futur"
      - name: exchangerate_from_EUR
        description: "Taux de change depuis EUR"
        tests:
          - not_null

sources:
  - name: bv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: cp_xml_validity
        description: "Table source de la validité temporelle des fichiers XML"
        columns:
          - name: booking_hk
            description: "Clé de hachage de la réservation"
          - name: file_name
            description: "Nom du fichier XML"
          - name: startdate
            description: "Date de début de validité"
          - name: enddate
            description: "Date de fin de validité"

  - name: wrk
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: lsat_cp_booking_cruise_vw
        description: "Vue des croisières de réservation"
        columns:
          - name: booking_hk
            description: "Clé de hachage de la réservation"
          - name: cruise_hk
            description: "Clé de hachage de la croisière"
          - name: file_name
            description: "Nom du fichier XML source"
          - name: date_departure
            description: "Date de départ de la croisière"
          - name: date_arrival
            description: "Date d'arrivée de la croisière"
          - name: itemstatuscode
            description: "Code de statut de l'élément"
          - name: cruise_bk
            description: "Clé métier de la croisière"

  - name: dv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: merged_account_and_contact
        description: "Table de gestion des fusions de comptes et de contacts Salesforce"
        columns:
          - name: ACCOUNTID_OR_CONTACTID
            description: "Identifiant du compte ou contact avant fusion"
          - name: ACCOUNTID_OR_CONTACTID_POST_MERGE
            description: "Identifiant du compte ou contact après fusion"
          - name: ACCOUNT_OR_CONTACT_HK
            description: "Clé de hachage du compte ou contact avant fusion"
          - name: ACCOUNT_OR_CONTACT_POST_MERGE_HK
            description: "Clé de hachage du compte ou contact après fusion"
          - name: TYPE_OF_OBJECT_POST_MERGE
            description: "Type d'objet après fusion (Account ou Contact)"
      - name: lsat_cp_booking_cruise
        description: "Table satellite des croisières"
      - name: link_booking__item__cruise__vessel__cabin
        description: "Table de liaison entre les réservations, les éléments, les croisières, les navires et les cabines"
      - name: hsat_cp_booking
        description: "Table satellite des réservations"

  - name: bv
    database: "{{ var('database') }}"
    schema: "{{ var('schema') }}"
    tables:
      - name: exchange_rate__to_eur__by_date
        description: "Table des taux de change vers EUR par date"
      - name: exchange_rate__futur_vw
        description: "Vue des taux de change futurs" 