version: 2

models:
  - name: d_financial_account
    description: "Table de base pour les comptes financiers"
    columns:
      - name: financial_account_code
        description: "Code du compte financier"
        tests:
          - unique
          - not_null
      - name: financial_account_label
        description: "Libelle du compte financier"
      - name: dt_creation
        description: "Date de creation du compte"
        tests:
          - is_valid_date
      - name: dt_update
        description: "Date de derniere mise a jour du compte"
        tests:
          - is_valid_date