{{
    config(
        materialized='table',
        schema='dv'
    )
}}

WITH source_data AS (
    SELECT 
        booking_hk::CHAR(40) AS booking_hk,
        load_dts::TIMESTAMP AS load_dts,
        load_end_dts::TIMESTAMP AS load_end_dts,
        del_flag::BOOLEAN AS del_flag,
        hash_diff::VARCHAR(40) AS hash_diff,
        record_source::VARCHAR(40) AS record_source,
        dv_run_id::INTEGER AS dv_run_id,
        file_name::VARCHAR(100) AS file_name,
        datetime_from_file_name::TIMESTAMP AS datetime_from_file_name,
        agencyid::VARCHAR(100) AS agencyid,
        bookingcontactname::VARCHAR(100) AS bookingcontactname,
        agentid::VARCHAR(100) AS agentid,
        agentfirstname::VARCHAR(100) AS agentfirstname,
        agentmiddlename::VARCHAR(100) AS agentmiddlename,
        agentlastname::VARCHAR(100) AS agentlastname,
        agentlanguagecode::VARCHAR(100) AS agentlanguagecode,
        consortiumcode::VARCHAR(100) AS consortiumcode,
        marketcode::VARCHAR(100) AS marketcode,
        bookingcurrencycode::VARCHAR(100) AS bookingcurrencycode,
        languagecode::VARCHAR(100) AS languagecode,
        officecode::VARCHAR(100) AS officecode,
        agencyreference::VARCHAR(100) AS agencyreference,
        marketname::VARCHAR(100) AS marketname,
        officename::VARCHAR(100) AS officename,
        sendemailconf::VARCHAR(100) AS sendemailconf,
        alphatoid::VARCHAR(100) AS alphatoid,
        crmid::VARCHAR(100) AS crmid,
        paxtype::VARCHAR(100) AS paxtype,
        bookingprofile::VARCHAR(100) AS bookingprofile,
        bookingsource::VARCHAR(100) AS bookingsource,
        sponsor::VARCHAR(100) AS sponsor,
        sponsorname::VARCHAR(100) AS sponsorname,
        bookingcontactpaxid::VARCHAR(100) AS bookingcontactpaxid,
        bookingcontactcrmid::VARCHAR(100) AS bookingcontactcrmid,
        endemailconf::VARCHAR(100) AS endemailconf,
        email::VARCHAR(100) AS email,
        documenttype::VARCHAR(100) AS documenttype,
        primaryproducttype::VARCHAR(100) AS primaryproducttype,
        primaryproductdesc::VARCHAR(100) AS primaryproductdesc,
        brandcode::VARCHAR(100) AS brandcode,
        brandname::VARCHAR(100) AS brandname,
        programcode::VARCHAR(100) AS programcode,
        programname::VARCHAR(100) AS programname,
        destinationcode::VARCHAR(100) AS destinationcode,
        destinationname::VARCHAR(100) AS destinationname,
        bkgdepartdate::VARCHAR(100) AS bkgdepartdate,
        bkgdepartdate__date::DATE AS bkgdepartdate__date,
        bkgreturndate::VARCHAR(100) AS bkgreturndate,
        bkgreturndate__date::DATE AS bkgreturndate__date,
        numberpax::DOUBLE PRECISION AS numberpax,
        agencysourcecode::VARCHAR(100) AS agencysourcecode,
        bookingpaxtype::VARCHAR(100) AS bookingpaxtype,
        costcenter::VARCHAR(100) AS costcenter,
        campaignid::VARCHAR(100) AS campaignid,
        campaigncode::VARCHAR(100) AS campaigncode,
        campaigndesc::VARCHAR(100) AS campaigndesc,
        primaryproductpromotionalcode::VARCHAR(100) AS primaryproductpromotionalcode,
        primaryproductpromotionaldesc::VARCHAR(100) AS primaryproductpromotionaldesc,
        primaryproductpromotionaltype::VARCHAR(100) AS primaryproductpromotionaltype,
        bkgdeptport::VARCHAR(100) AS bkgdeptport,
        stdbkgdeptport::VARCHAR(100) AS stdbkgdeptport,
        bkgarrport::VARCHAR(100) AS bkgarrport,
        stdbkgarrport::VARCHAR(100) AS stdbkgarrport,
        bookingstatuscode::VARCHAR(100) AS bookingstatuscode,
        bookingstatusdesc::VARCHAR(100) AS bookingstatusdesc,
        cancelreason::VARCHAR(100) AS cancelreason,
        paymentstatuscode::VARCHAR(100) AS paymentstatuscode,
        paymentstatusdescription::VARCHAR(100) AS paymentstatusdescription,
        bookingtype::VARCHAR(100) AS bookingtype,
        bookeddate::VARCHAR(100) AS bookeddate,
        bookeddate__date::DATE AS bookeddate__date,
        groupid::VARCHAR(100) AS groupid,
        grouptype::VARCHAR(100) AS grouptype,
        invoicenumber::VARCHAR(100) AS invoicenumber,
        invoicedate::VARCHAR(100) AS invoicedate,
        invoicedate__date::DATE AS invoicedate__date,
        totalinvoiceamount::VARCHAR(100) AS totalinvoiceamount,
        totalinvoiceamount__number::DOUBLE PRECISION AS totalinvoiceamount__number,
        createdbyname::VARCHAR(100) AS createdbyname,
        createddate::VARCHAR(100) AS createddate,
        createddate__date::DATE AS createddate__date,
        createdby::VARCHAR(100) AS createdby,
        lastchangeddate::VARCHAR(100) AS lastchangeddate,
        lastchangeddate__date::DATE AS lastchangeddate__date,
        lastchangedby::VARCHAR(100) AS lastchangedby,
        lastchangedbyname::VARCHAR(100) AS lastchangedbyname,
        businessreference::VARCHAR(100) AS businessreference,
        businessreportername::VARCHAR(100) AS businessreportername,
        invoicetype::VARCHAR(100) AS invoicetype,
        totalgrossprice::VARCHAR(100) AS totalgrossprice,
        totalgrossprice__number::DOUBLE PRECISION AS totalgrossprice__number,
        totalnetprice::VARCHAR(100) AS totalnetprice,
        totalnetprice__number::DOUBLE PRECISION AS totalnetprice__number,
        totalcommissionamount::VARCHAR(100) AS totalcommissionamount,
        totalcommissionamount__number::DOUBLE PRECISION AS totalcommissionamount__number,
        stdcommission::VARCHAR(100) AS stdcommission,
        stdcommission__number::DOUBLE PRECISION AS stdcommission__number,
        totalbonuscommissionamount::VARCHAR(100) AS totalbonuscommissionamount,
        totalbonuscommissionamount__number::DOUBLE PRECISION AS totalbonuscommissionamount__number,
        depositamountdue::VARCHAR(100) AS depositamountdue,
        depositamountdue__number::DOUBLE PRECISION AS depositamountdue__number,
        depositduedate::VARCHAR(100) AS depositduedate,
        depositduedate__date::DATE AS depositduedate__date,
        totalpaymentsreceived::VARCHAR(100) AS totalpaymentsreceived,
        totalpaymentsreceived__number::DOUBLE PRECISION AS totalpaymentsreceived__number,
        grossbalancedue::VARCHAR(100) AS grossbalancedue,
        grossbalancedue__number::DOUBLE PRECISION AS grossbalancedue__number,
        netbalancedue::VARCHAR(100) AS netbalancedue,
        netbalancedue__number::DOUBLE PRECISION AS netbalancedue__number,
        optionexpiresdate::VARCHAR(100) AS optionexpiresdate,
        optionexpiresdate__date::DATE AS optionexpiresdate__date,
        finalpaymentdate::VARCHAR(100) AS finalpaymentdate,
        finalpaymentdate__date::DATE AS finalpaymentdate__date,
        vatamount::VARCHAR(100) AS vatamount,
        vatamount__number::DOUBLE PRECISION AS vatamount__number,
        totalothertaxamount::VARCHAR(100) AS totalothertaxamount,
        totalothertaxamount__number::DOUBLE PRECISION AS totalothertaxamount__number,
        addressline1::VARCHAR(100) AS addressline1,
        addressline2::VARCHAR(100) AS addressline2,
        city::VARCHAR(100) AS city,
        stateprovince::VARCHAR(100) AS stateprovince,
        districtcode::VARCHAR(100) AS districtcode,
        zippostalcode::VARCHAR(100) AS zippostalcode,
        countrycode::VARCHAR(100) AS countrycode,
        telephoneno::VARCHAR(100) AS telephoneno,
        faxno::VARCHAR(100) AS faxno,
        email_address::VARCHAR(100) AS email_address,
        traveldocpreference::VARCHAR(100) AS traveldocpreference,
        paymentduedate::VARCHAR(100) AS paymentduedate,
        paymentduedate__date::DATE AS paymentduedate__date,
        reminder1::VARCHAR(100) AS reminder1,
        reminder2::VARCHAR(100) AS reminder2,
        reminder3::VARCHAR(100) AS reminder3,
        emailsent::VARCHAR(100) AS emailsent,
        papersent::VARCHAR(100) AS papersent,
        ponantaccount::VARCHAR(100) AS ponantaccount,
        fullypaid::VARCHAR(100) AS fullypaid,
        invoiced::VARCHAR(100) AS invoiced,
        agencyname::VARCHAR(100) AS agencyname,
        addressline1_agency::VARCHAR(255) AS addressline1_agency,
        addressline2_agency::VARCHAR(255) AS addressline2_agency,
        city_agency::VARCHAR(100) AS city_agency,
        stateprovince_agency::VARCHAR(100) AS stateprovince_agency,
        districtcode_agency::VARCHAR(100) AS districtcode_agency,
        zippostalcode_agency::VARCHAR(100) AS zippostalcode_agency,
        countrycode_agency::VARCHAR(100) AS countrycode_agency,
        telephoneno_agency::VARCHAR(100) AS telephoneno_agency,
        telephoneno2_agency::VARCHAR(100) AS telephoneno2_agency,
        faxno_agency::VARCHAR(100) AS faxno_agency,
        email_agency::VARCHAR(100) AS email_agency,
        senddocstopax_agency::VARCHAR(100) AS senddocstopax_agency,
        maskcommission_agency::VARCHAR(100) AS maskcommission_agency,
        IDIBS::VARCHAR(100) AS IDIBS
    FROM {{ source('dv', 'hsat_cp_booking') }}
)

SELECT 
    * 
FROM source_data 