version: 2

sources:
  - name: dwh
    database: dev
    schema: dwh
    tables:
      - name: d_financial_account

  - name: dv
    database: dev
    schema: dv
    tables:
      - name: hub_booking
      - name: hub_brand
      - name: hub_budget_line
      - name: hub_budget_pickup
      - name: hub_budget_version
      - name: hub_cabin_category
      - name: hub_cabin
      - name: hub_campaign
      - name: hub_chargetype
      - name: hub_clusteragency
      - name: hub_configuration
      - name: hub_contact
      - name: hub_country
      - name: hub_cruise_cluster
      - name: hub_currency
      - name: hub_discount
      - name: hub_eniram_vessel
      - name: hub_erosionhorsibs
      - name: hub_finance_rate
      - name: hub_flight
      - name: hub_fms_acc
      - name: hub_fms_acx
      - name: hub_fms_cruise
      - name: hub_fms_dep
      - name: hub_fms_epo
      - name: hub_fms_dem
      - name: hub_fms_ese
      - name: hub_fms_pos
      - name: hub_fms_shp
      - name: hub_fms_spa
      - name: hub_fms_sscd
      - name: hub_fms_ssci
      - name: hub_fms_spr
      - name: hub_group
      - name: hub_item
      - name: hub_item_new
      - name: hub_item_old
      - name: hub_kardex
      - name: hub_mm_cruise
      - name: hub_mr_cabin_category
      - name: hub_mr_cabin_number
      - name: hub_mr_vessel
      - name: hub_mr_vessel_configuration
      - name: hub_mr_vessel_type
      - name: hub_sf_account
      - name: hub_sf_booking_line_item
      - name: hub_sf_campaign
      - name: hub_sf_campaignmember
      - name: hub_sf_campaignsource
      - name: hub_sf_case
      - name: hub_sf_commercial_gesture
      - name: hub_sf_contact
      - name: hub_sf_cruise_scope
      - name: hub_sf_deleted_campaign_members
      - name: hub_sf_event
      - name: hub_sf_household
      - name: hub_sf_kardex
      - name: hub_sf_lead
      - name: hub_sf_opportunity
      - name: hub_sf_passenger_roles
      - name: hub_sf_recordtype
      - name: hub_sf_subscription
      - name: hub_sf_task
      - name: hub_sf_user
      - name: hub_ns_currency
      - name: hub_ns_transaction
      - name: hub_ns_transaction_line
      - name: hub_cuise
      

      - name: hsat_cp_booking
      - name: hsat_cp_product
      - name: hsat_sf_account
      - name: hsat_MM_cruise
      - name: hsat_MR_cabin_number
      - name: hsat_MR_vessel_configuration
      
      - name: link_cabincat__mr_cabin_number__mr_vesconfig
      - name: link_configuration__mr_vessel__mr_vessel_configuration
      - name: lsat_MM_cruise
      - name: link_vessel__mr_vessel__mr_vessel_type
      - name: link_sf_subscription__brand
      - name: lsat_cp_booking_cruise
      - name: link_booking__item__cruise__vessel__cabin




  - name: bv
    database: dev
    schema: bv
    tables:
      - name: cp_xml_validity