version: 2

sources:
  - name: dwh
    database: dev
    schema: dwh
    tables:
      - name: d_financial_account
  
  - name: dm
    database: dev
    schema: dm
    tables:
      - name: f_facts

      - name: d_booking

      - name: d_group

      - name: d_item

      - name: d_cruise

      - name: d_booking__cruise

      - name: d_booking__cruise__participant

      - name: d_account_b2b

      - name: d_person_account

      - name: d_booking_participant

      - name: d_fx_proforma

  - name: dv
    database: dev
    schema: dv
    tables:
      - name: hub_booking
      - name: hub_brand
      - name: hub_budget_line
      - name: hub_budget_pickup
      - name: hub_budget_version
      - name: hub_cabin_category
      - name: hub_cabin
      - name: hub_campaign
      - name: hub_chargetype
      - name: hub_clusteragency
      - name: hub_configuration
      - name: hub_contact
      - name: hub_country
      - name: hub_cruise
      - name: hub_cruise_cluster
      - name: hub_currency
      - name: hub_discount
      - name: hub_eniram_vessel
      - name: hub_erosionhorsibs
      - name: hub_finance_rate
      - name: hub_flight
      - name: hub_fms_acc
      - name: hub_fms_acx
      - name: hub_fms_cruise
      - name: hub_fms_dep
      - name: hub_fms_epo
      - name: hub_fms_dem
      - name: hub_fms_ese
      - name: hub_fms_pos
      - name: hub_fms_shp
      - name: hub_fms_spa
      - name: hub_fms_sscd
      - name: hub_fms_ssci
      - name: hub_fms_spr
      - name: hub_group
      - name: hub_item
      - name: hub_item_new
      - name: hub_item_old
      - name: hub_kardex
      - name: hub_mm_cruise
      - name: hub_mr_cabin_category
      - name: hub_mr_cabin_number
      - name: hub_mr_vessel
      - name: hub_mr_vessel_configuration
      - name: hub_mr_vessel_type
      - name: hub_sf_account
      - name: hub_sf_booking_line_item
      - name: hub_sf_campaign
      - name: hub_sf_campaignmember
      - name: hub_sf_campaignsource
      - name: hub_sf_case
      - name: hub_sf_commercial_gesture
      - name: hub_sf_contact
      - name: hub_sf_cruise_scope
      - name: hub_sf_deleted_campaign_members
      - name: hub_sf_event
      - name: hub_sf_household
      - name: hub_sf_kardex
      - name: hub_sf_lead
      - name: hub_sf_opportunity
      - name: hub_sf_passenger_roles
      - name: hub_sf_recordtype
      - name: hub_sf_subscription
      - name: hub_sf_task
      - name: hub_sf_user
      - name: hub_ns_currency
      - name: hub_ns_transaction
      - name: hub_ns_transaction_line
      - name: hub_vessel
      - name: hub_cabin_cp__mm__mr

      
      - name: link_cabincat__mr_cabin_number__mr_vesconfig
      - name: link_configuration__mr_vessel__mr_vessel_configuration
      - name: lsat_MM_cruise
      - name: link_vessel__mr_vessel__mr_vessel_type
      - name: link_sf_subscription__brand
      - name: lsat_cp_booking_cruise
      - name: link_booking__item__cruise__vessel__cabin
      - name: link_booking__contact
      - name: link_booking__item
      - name: link_booking__item__contact
      - name: link_booking__item__contact_test_new
      - name: link_booking__item__contact_test_old
      - name: link_booking__item__contact__chargetype
      - name: link_booking__item__contact__chargetype__discount
      - name: link_booking__item__flight
      - name: link_budget_version__budget_line
      - name: link_cabincat__mr_cabincat__mr_vessel_config
      - name: link_cabin_category__vessel__configuration
      - name: link_cabin__vessel__configuration
      - name: link_cruise__cruise_cluster
      - name: link_currency__finance_rate
      - name: link_fms_cruise__fms_shp
      - name: link_fms_epo__fms_shp__fms_pos__fms_ese
      - name: link_fms_ese__fms_shp
      - name: link_fms_pos__fms_cruise__fms_shp__fms_dep__fms_dem
      - name: link_fms_spa__fms_shp__fms_acc
      - name: link_fms_spr__fms_shp__fms_dep__fms_pos__fms_spa
      - name: link_fms_sscd__fms_ssci
      - name: link_fms_ssci__fms_shp__fms_cruise__fms_acc
      - name: link_group__cabin_category
      - name: link_mm_cruise__cruise__vessel
      - name: link_ns_currency__currency
      - name: link_ns_currency__ns_currency
      - name: link_ns_transaction__ns_transaction_line
      - name: link_sf_account__sf_user
      - name: link_sf_booking_line_item__sf_opportunity
      - name: link_sf_campaign__campaign__sf_user
      - name: link_sf_campaignmember__sf_campaign
      - name: link_sf_case__sf_user__sf_recordtype
      - name: link_sf_commercial_gesture__sf_account
      - name: link_sf_commercial_gesture__sf_case__sf_account
      - name: link_sf_contact__sf_account__sf_user
      - name: link_sf_cruise_scope__campaign
      - name: link_sf_deleted_campaign_members__sf_campaignmember
      - name: link_sf_event__sf_user
      - name: link_sf_event__sf_user__sf_recordtype
      - name: link_sf_household__sf_account__sf_account
      - name: link_sf_kardex__kardex__sf_account__sf_user
      - name: link_sf_lead__sf_user
      - name: link_sf_passenger_roles__sf_opportunity__sf_account
      - name: link_sf_task__sf_user
      - name: link_sf_task__sf_user__sf_recordtype
      - name: link_vessel__configuration

      

      - name: hsat_cp_booking
      - name: hsat_cp_product
      - name: hsat_sf_account
      - name: hsat_MM_cruise
      - name: hsat_mr_cabin_number
      - name: hsat_mr_cabin_category
      - name: hsat_mr_vessel_configuration
      - name: hsat_mr_vessel_type
      - name: hsat_mr_vessel
      - name: hsat_Eniram_VesselList
      - name: hsat_cp_groupcontractinfo
      - name: hsat_cp_bookingstatusdate
      - name: hsat_cp_bookingstatus
      - name: hsat_cp_booking_participant_followup
      - name: hsat_cp_product_theme
      - name: hsat_FMS_acc
      - name: hsat_sf_account_staging
      - name: hsat_sf_campaign
      - name: hsat_sf_campaignmember
      - name: hsat_sf_campaignsource
      - name: hsat_sf_case
      - name: hsat_sf_commercial_gesture
      - name: hsat_sf_contact
      - name: hsat_sf_cruise_scope
      - name: hsat_sf_deleted_campaign_members
      - name: hsat_sf_event
      - name: hsat_sf_household
      - name: hsat_sf_kardex
      - name: hsat_sf_lead
      - name: hsat_sf_opportunity
      - name: hsat_sf_passenger_roles
      - name: hsat_sf_recordtype
      - name: hsat_sf_subscription
      - name: hsat_sf_task
      - name: hsat_sf_user
      - name: hsat_sf_voiture




  - name: bv
    database: dev
    schema: bv
    tables:
      - name: cp_xml_validity
      - name: hub_cabin_cp__mm__mr